# Generated by Django 4.2.4 on 2023-09-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Academics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, verbose_name="University/School Name"
                    ),
                ),
                (
                    "qualification",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Qualification"
                    ),
                ),
                ("start_date", models.DateField(null=True, verbose_name="Start Date")),
                ("end_date", models.DateField(null=True, verbose_name="End Date")),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Grade / Mark",
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="Remarks"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attachments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(max_length=125, verbose_name="Document Type"),
                ),
                (
                    "document",
                    models.FileField(
                        null=True, upload_to="documents/", verbose_name="Document"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now=True, verbose_name="Uploaded At"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnglishLanguageRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidate_id",
                    models.CharField(
                        max_length=125, null=True, verbose_name="Candidate ID"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(null=True, verbose_name="Expiry date"),
                ),
            ],
        ),
    ]
